export const provinceData = {
  Архангай: "Arhangai",
  "Баян-Өлгий": "Bayanulgii",
  Баянхонгор: "Bayanhongor",
  Булган: "Bulgan",
  "Говь-Алтай": "Govialtai",
  Говьсүмбэр: "Govisumber",
  "Дархан-Уул": "Darhanuul",
  Дорноговь: "Dornogovi",
  Дорнод: "Dornod",
  Дундговь: "Dundgovi",
  Завхан: "Zavhan",
  Орхон: "Orhon",
  Өвөрхангай: "Uvurhangai",
  Өмнөговь: "Umnugovi",
  Сүхбаатар: "Suhbaatar",
  Сэлэнгэ: "Selenge",
  Төв: "Tuv",
  Увс: "Uvs",
  Ховд: "Hovd",
  Хөвсгөл: "Huvsgul",
  Хэнтий: "Hentii",
};
